[package]
name = "fsling"
version = "0.1.0"
authors = ["Ellie Huxtable <e@elm.sh>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.1"
notify = "4.0.15"
